### ISSUE TITLE
document installation of cubature

### ISSUE THREAD

**Issue by marksantcroos** [iljah/hdintegrator#10]

**Comment by iljah** [comment]
I wasn't using/maintaining integrand(s) requiring cubature so I removed them instead.

**Comment by marksantcroos** [comment]
```
make: *** No rule to make target `integrands/turbulence3_hcubature', needed by `all'.  Stop.
```

**Comment by iljah** [comment]
Fixed by https://github.com/iljah/hdintegrator/commit/3ddc7e2ec674499dc8ddb2c6add87a80da6d2c15 thanks.

**Comment by marksantcroos** [comment]
Thanks, build works now!
