### ISSUE TITLE
ld: library not found for -lboost_program_options

### ISSUE THREAD

**Issue by marksantcroos** [iljah/hdintegrator#12]
Which dependency is missing here?

```
$ make
g++ -std=c++14 -O3 -march=native -W -Wall -Wextra -Wpedantic integrands/burgers.cpp -o integrands/burgers_plain integrands/gsl/plain2.c -DMETHOD=1 -I integrands/gsl -lgsl -lgslcblas -lboost_program_options
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
ld: library not found for -lboost_program_options
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [integrands/burgers_plain] Error 1
```

**Comment by iljah** [comment]
Boost program options, added to install docs in https://github.com/iljah/hdintegrator/commit/a6f5b63a1c4a0a045ce3c23ff8da14b9097b78df

**Comment by marksantcroos** [comment]
I had to change the Makefile and change `-lboost_program_options` into `-lboost_program_options-mt` to get it compiled. But this might be an issue of how boost is installed on my machine (through macports).

**Comment by iljah** [comment]
Fixed by https://github.com/iljah/hdintegrator/commit/3ddc7e2ec674499dc8ddb2c6add87a80da6d2c15 thanks. Now you can customize library argument for boost with

    make BOOST_LDFLAGS=-lboost_program_options-mt
