### ISSUE TITLE
tabs vs spaces

### ISSUE THREAD

**Issue by marksantcroos** [iljah/hdintegrator#14]
Do you have any reason to use tabs instead of spaces?

It gave me a hard time to make the changes you suggested on #13.

Also see https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces

**Comment by iljah** [comment]
I'm using tabs so that the width of indentation can be customized without changing the code. Can you elaborate on why the changes in #13 were difficult? For me it was easy because the tabs were preserved so the replacement code worked as is.

**Comment by marksantcroos** [comment]
Because my main editor is configured confirming to pep8.

**Comment by iljah** [comment]
I didn't see copy & paste mentioned in pep8 but it does say that tabs should be used to remain consistent with code already indented with tabs. Do you mean that your configuration converted tabs to spaces automatically? Shouldn't that apply to pasted code also?

In any case the tabs vs. spaces question was closed on stackexchange as not constructive so there are probably valid arguments on both sides but for now I'll stick to tabs.

**Comment by marksantcroos** [comment]
I can't force you, but as a piece of feedback, for me it would be a showstopper to contribute to your project.

**Comment by iljah** [comment]
Ok thanks for the input, I'll keep it in mind. Is this the case with any language or only python?

**Comment by marksantcroos** [comment]
With python in particular. The reference to "code that was already indented with tabs" referred to code already written at the time that pep8 was published.
