### ISSUE TITLE
use markdown for readme, install, etc

### ISSUE THREAD

**Issue by marksantcroos** [iljah/hdintegrator#2]
Please use markdown to increase the readability of the documentation.

**Comment by iljah** [comment]
Fixed in https://github.com/iljah/hdintegrator/commit/51b0ca9ce19dcbcd129360a78a53a25ee7e88836 and previous commits.

**Comment by marksantcroos** [comment]
Thanks! Hopefully that didn't feel like a chore but I hope you consider it an improvement for yourself too! :-)

**Comment by iljah** [comment]
Good suggestion, I was planning to start using markdown at some point.
