### ISSUE TITLE
recommend virtual environments in installation procedure

### ISSUE THREAD

**Issue by marksantcroos** [iljah/hdintegrator#3]
Instead of having people mess up their system environment, I would suggest you document the installation using virtual environments (or anaconda's equivalent).

**Comment by iljah** [comment]
I'll add instructions for installing required python libraries under home directory but at least on fedora all requirements are available from distribution repositories so I wouldn't exactly call installing them "messing up the system environment".

**Comment by iljah** [comment]
Fixed by https://github.com/iljah/hdintegrator/commit/9ced7419b692788a313c325ec9a54224f0d6824c
