### ISSUE TITLE
license file is called COPYING instead of LICENSE

### ISSUE THREAD

**Issue by marksantcroos** [iljah/hdintegrator#4]

**Comment by iljah** [comment]
FSF [instructions](https://www.gnu.org/licenses/gpl-howto.html) say to use a file named COPYING, would a symlink to LICENSE work?

**Comment by marksantcroos** [comment]
I suspected so much, as COPYING sounds more opinionated than LICENSE.

Honestly I don't feel strong about it. In fact, [Github documentation](https://help.github.com/articles/licensing-a-repository/) actually suggests adding a `LICENSE.md` or `LICENSE.txt`, which is not strictly the same as the review template either.

@danielskatz Maybe something to change in the review template?

**Comment by danielskatz** [comment]
Given that I see in the instructions

>You should also include a copy of the license itself somewhere in the distribution of your program. All programs, whether they are released under the GPL or LGPL, should include the text version of the GPL. In GNU programs we conventionally put the license in a file called COPYING.

it seems clear that the use of copying is a convention, not a requirement, and having an additional file called LICENSE, either that's a copy of COPYING or a simlink, should be fine.

Re the JOSS review template: LICENSE vs LICENSE.txt is not much of a concern for JOSS.  But LICENSE.md would not be ok - we say that this should be plaintext...

**Comment by iljah** [comment]
Fixed by https://github.com/iljah/hdintegrator/commit/ef00d3d8f04fac9405bb2feaf22e4ec70e0fc01a
