### ISSUE TITLE
installation is not really documented

### ISSUE THREAD

**Issue by marksantcroos** [iljah/hdintegrator#5]
The INSTALL provides some details about the software requirements, but doesn't actually specify how to install the hdintegrator software itself.

**Comment by iljah** [comment]
Aside from checking out the repository there's nothing to install if one is using e.g. a python integrand. For included C++ integrand the file [does](https://github.com/iljah/hdintegrator/blob/master/INSTALL#L20) mention compiling them with (gnu) make using the provided makefile. I'll add an explicit mention of potentially not requiring any installation when I change the files to markdown format.

**Comment by marksantcroos** [comment]
That needs to be changed then. I don't want to use code directly from a checkout.

**Comment by iljah** [comment]
I'll use https://github.com/iljah/hdintegrator/issues/1 to track installability.
