### ISSUE TITLE
no (documented) tests available

### ISSUE THREAD

**Issue by marksantcroos** [iljah/hdintegrator#6]

**Comment by iljah** [comment]
Do you mean something else besides or in addition to [this](https://github.com/iljah/hdintegrator/blob/a8e1d763790582a12f41ad93f4f93e3e438768e3/INSTALL#L27)?

**Comment by marksantcroos** [comment]
Something more automated that returns True or False.

**Comment by iljah** [comment]
Fixed in https://github.com/iljah/hdintegrator/commit/7e10d09cb233b20d33441bc66151881a39a99177. Pytest at least doesn't support testing mpi4py programs so I decided a simple addition to the makefile would suffice.
