### ISSUE TITLE
local library / include path location

### ISSUE THREAD

**Issue by marksantcroos** [iljah/hdintegrator#9]
Can you possibly change the Makefile and/or document how to pick up the installed GSL files?

I had to set these environment variables to get passed:
```
export CPATH=/opt/local/include
export LIBRARY_PATH=/opt/local/lib
```

**Comment by iljah** [comment]
Fixed by https://github.com/iljah/hdintegrator/commit/a48acc6b912c75c0735175e9932e37bf5e0245a9 , now you can give those to make, e.g.

    make CPPFLAGS=-I/opt/local/include ...
